<?php
/**
 * @file
 * Simple module Rn Page for test task.
 */

/**
 * Implements hook_menu().
 */
function rn_page_menu() {
  $items['drupal-test-task'] = array(
    'title' => 'People',
    'description' => 'List of Users',
    'page callback' => 'rn_page_user_list',
    'access arguments' => array('administer users'),
    'file' => 'rn_page.admin.inc',
  );

  $items['drupal-test-form'] = array(
    'title' => 'Test Form',
    'description' => 'Test select in form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rn_page_generate_test_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function rn_page_preprocess_page(&$variables) {
  drupal_add_library('system', 'jquery.once');
  drupal_add_library('system', 'jquery');
  drupal_add_css('//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css', 'external');
  drupal_add_js('//code.jquery.com/ui/1.12.1/jquery-ui.js', 'external');
}

/**
 * Form builder; Provide the form for test selectmenu.
 */
function rn_page_generate_test_form($form, &$form_state) {

  $options = array('Slower', 'Slow', 'Medium', 'Fast', 'Faster');
  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Test options'),
  );
  $form['options']['speed'] = array(
    '#type' => 'select',
    '#title' => t('Select a speed'),
    '#options' => $options,
    '#default_value' => 2,
  );
  $form['options']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );

  return $form;
}
